### ISSUE TITLE
build for EL6

### ISSUE THREAD

**Issue by carlwgeorge** [iusrepo/python36u#1]
Currently we only build this package for EL7.  As requested in iuscommunity/wishlist#129, some users would like to use it on EL6 as well.  Originally this was blocked by an upstream [minimum sqlite requirement](http://bugs.python.org/issue29098), but that was [removed in 3.6.1](http://bugs.python.org/issue28518).

**Comment by carlwgeorge** [comment]
When building this in an EL6 mock chroot under Fedora 25, the test suite aborts with a segmentation fault.

<details>
<summary>testInfiniteRecursion (test.test_exceptions.ExceptionTests)</summary>

```
testInfiniteRecursion (test.test_exceptions.ExceptionTests) ... Fatal Python error: Segmentation fault
Current thread 0x00007f8cbebf7700 (most recent call first):
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  File "/builddir/build/BUILD/Python-3.6.1/Lib/test/test_exceptions.py", line 490 in f
  ...
/var/tmp/rpm-tmp.893BEM: line 40: 14082 Segmentation fault      (core dumped) WITHIN_PYTHON_RPM_BUILD= LD_LIBRARY_PATH=$ConfDir $ConfDir/python -m test.regrtest --verbose --findleaks -x test_distutils
```

</details>


However, when built directly with rpmbuild on EL6, everything passes.  I'm going to do a bit more research to determine if this test is appropriate to skip.

**Comment by mjholtkamp** [comment]
Could it be that the EL6 mock chroot has a much lower stack size than a native EL6 host? According to http://bugs.python.org/issue1110055 a segfault can happen if the recursion limit (apparently defaults to 1000) is too high for the allowed stack size.

Since chroot does not limit stack size, it might be Fedora 25, or the script (if any) that starts up the chroot for you.

Maybe you could compare the stack size between (a process in) the chroot and the native EL6?

**Comment by carlwgeorge** [comment]
Small update, I also found a few tests fail only on EL6 32bit.

<details>
<summary>test_specific_values (test.test_cmath.CMathTests)</summary>

```
test_specific_values (test.test_cmath.CMathTests) ... FAIL
======================================================================
FAIL: test_specific_values (test.test_cmath.CMathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Python-3.6.0/Lib/test/test_cmath.py", line 418, in test_specific_values
    msg=error_message)
  File "/builddir/build/BUILD/Python-3.6.0/Lib/test/test_cmath.py", line 149, in rAssertAlmostEqual
    '{!r} and {!r} are not sufficiently close'.format(a, b))
AssertionError: tan0064: tan(complex(1.5707963267948961, 0.0))
Expected: complex(1978937966095219.0, 0.0)
Received: complex(1978945885716843.0, 0.0)
Received value insufficiently close to expected value.
----------------------------------------------------------------------
```

</details>

<details>
<summary>test_testfile (test.test_math.MathTests)</summary>

```
test_testfile (test.test_math.MathTests) ... FAIL
======================================================================
FAIL: test_testfile (test.test_math.MathTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Python-3.6.0/Lib/test/test_math.py", line 1220, in test_testfile
    '\n  '.join(failures))
AssertionError: Failures in test_testfile:
  tan0064: tan(1.5707963267948961): expected 1978937966095219.0, got 1978945885716843.0 (error = 7.92e+09 (31678486496 ulps); permitted error = 0 or 5 ulps)
----------------------------------------------------------------------
```

</details>


Researching those a bit indicates that they should be safe to skip.  Upstream already [skips those by default on older versions of OSX](https://bugs.python.org/issue26040).

**Comment by mjholtkamp** [comment]
Thanks for the update Carl! I had no idea I caused so much trouble to you by asking you to do this, I thought it would be a trivial action, but apparently it was not that easy. I appreciate you taking the time for this :)

**Comment by carlwgeorge** [comment]
It's quite alright, nothing seems to be an outright show stopper so far.  Things just take time sometimes.

By the way, you were right by the way about the stack size.  My Fedora 25 server has a stack size of 8192, where as my CentOS 6 server is 10240.

**Comment by mjholtkamp** [comment]
Ah, good news indeed! I'll keep an eye on it. Looking forward to your next update.

**Comment by carlwgeorge** [comment]
I have completed [3.6.1-2](https://github.com/iuscommunity-pkg/python36u/releases/tag/3.6.1-2) with EL6 support.  It will move to the testing repos during tonight's automation.  Let us know how it works for you.

**Comment by mjholtkamp** [comment]
Awesome! I'll try it out on Monday :) Thanks for your effort!

**Comment by mjholtkamp** [comment]
Works like a charm! What happens next? I assume we can expect this in stable in a short while?

**Comment by carlwgeorge** [comment]
Thanks for the quick feedback @mjholtkamp.  I'll set that release to move to the stable repos during tonight's automation.

If there are other python36u-* packages you need, open issues as needed on the respective repos in the [iuscommunity-pkg](https://github.com/iuscommunity-pkg) organization.

Thanks for participating in IUS!
